const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  selectDirectory: () => ipcRenderer.invoke('fs:select-directory'),
  selectFile: (filters) => ipcRenderer.invoke('fs:select-file', { filters }),
  selectFiles: (filters) => ipcRenderer.invoke('fs:select-files', { filters }),
  saveImage: (filePath, dataUrl) => ipcRenderer.invoke('fs:save-image', { filePath, dataUrl }),
  saveCompositeImage: (filePath, dataUrl, maxSizeKb) => ipcRenderer.invoke('composite:save-image', { filePath, dataUrl, maxSizeKb }),
  saveJson: (filePath, data) => ipcRenderer.invoke('fs:save-json', { filePath, data }),
  saveText: (filePath, content) => ipcRenderer.invoke('fs:save-text', { filePath, content }),
  ensureDir: (dirPath) => ipcRenderer.invoke('fs:ensure-dir', { dirPath }),
  removeEmptyDir: (dirPath) => ipcRenderer.invoke('fs:remove-empty-dir', { dirPath }),
  pathJoin: (...paths) => ipcRenderer.invoke('fs:path-join', { paths }),
  checkExists: (filePath) => ipcRenderer.invoke('fs:check-exists', { filePath }),
  readDir: (dirPath) => ipcRenderer.invoke('fs:read-dir', { dirPath }),
  readImageFile: (filePath) => ipcRenderer.invoke('composite:read-image-file', { filePath }),
  listImageFiles: (dirPath) => ipcRenderer.invoke('composite:list-image-files', { dirPath }),
  listCompositeBackgroundFiles: (dirPath, recursive) => ipcRenderer.invoke('composite:list-background-files', { dirPath, recursive }),
  scanEnteredCompositeBackgroundFolder: (dirPath, recursive) => ipcRenderer.invoke('composite:scan-entered-background-folder', { dirPath, recursive }),
  pickImageFile: (input) => ipcRenderer.invoke('composite:pick-image-file', input),
  deleteCompositeFiles: (filePaths) => ipcRenderer.invoke('composite:delete-files', { filePaths }),
  distributeFile: (payload) => ipcRenderer.invoke('composite:distribute-file', payload),
  readFileBuffer: (filePath) => ipcRenderer.invoke('fs:read-file-buffer', { filePath }),
  getDefaultPath: () => ipcRenderer.invoke('fs:get-default-path'),
  openInExplorer: (filePath) => ipcRenderer.invoke('fs:open-in-explorer', { filePath }),
  getLocalSavePath: () => ipcRenderer.invoke('store:get-local-save-path'),
  setLocalSavePath: (path) => ipcRenderer.invoke('store:set-local-save-path', { path }),
  copyCacheToRoot: (newRoot) => ipcRenderer.invoke('store:copy-cache-to-root', { newRoot }),
  readJsonText: (filePath) => ipcRenderer.invoke('fs:read-json-text', { filePath }),
  writeJsonText: (filePath, content, backupIntervalOrSkip) => ipcRenderer.invoke('fs:write-json-text', { filePath, content, skipBackup: typeof backupIntervalOrSkip === 'boolean' ? backupIntervalOrSkip : undefined, backupInterval: typeof backupIntervalOrSkip === 'number' ? backupIntervalOrSkip : undefined }),
  listBackups: (filePath) => ipcRenderer.invoke('fs:list-backups', { filePath }),
  checkBackupHasData: (backupPath) => ipcRenderer.invoke('fs:check-backup-has-data', { backupPath }),
  restoreFromBackup: (backupPath, targetPath) => ipcRenderer.invoke('fs:restore-from-backup', { backupPath, targetPath }),
  deleteBackup: (backupPath) => ipcRenderer.invoke('fs:delete-backup', { backupPath }),
  saveZipBuffer: (filePath, buffer) => ipcRenderer.invoke('fs:save-zip-buffer', { filePath, buffer }),
  selectZipSavePath: (defaultName) => ipcRenderer.invoke('fs:select-zip-save-path', { defaultName }),
  exportZipToPath: (request) => ipcRenderer.invoke('fs:export-zip', request),
  deleteCacheImages: (filePaths) => ipcRenderer.invoke('store:delete-cache-images', { filePaths }),
  reconcileCacheImages: (referencedFileNames) => ipcRenderer.invoke('store:reconcile-cache-images', { referencedFileNames }),
  getDesktopPath: () => ipcRenderer.invoke('fs:get-desktop-path'),
  onUpdateStatus: (callback) => {
    const handler = (_event, ...args) => callback(...args)
    ipcRenderer.on('update:status', handler)
    return () => ipcRenderer.removeListener('update:status', handler)
  },
  checkForUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  getAppVersion: () => ipcRenderer.invoke('app:get-version'),
  getStartupMode: () => ipcRenderer.invoke('app:get-startup-mode'),
  isElectron: true,
})
