const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  selectDirectory: () => ipcRenderer.invoke('fs:select-directory'),
  saveImage: (filePath, dataUrl) => ipcRenderer.invoke('fs:save-image', { filePath, dataUrl }),
  saveJson: (filePath, data) => ipcRenderer.invoke('fs:save-json', { filePath, data }),
  saveText: (filePath, content) => ipcRenderer.invoke('fs:save-text', { filePath, content }),
  ensureDir: (dirPath) => ipcRenderer.invoke('fs:ensure-dir', { dirPath }),
  pathJoin: (...paths) => ipcRenderer.invoke('fs:path-join', { paths }),
  checkExists: (filePath) => ipcRenderer.invoke('fs:check-exists', { filePath }),
  readDir: (dirPath) => ipcRenderer.invoke('fs:read-dir', { dirPath }),
  readFileBuffer: (filePath) => ipcRenderer.invoke('fs:read-file-buffer', { filePath }),
  getDefaultPath: () => ipcRenderer.invoke('fs:get-default-path'),
  openInExplorer: (filePath) => ipcRenderer.invoke('fs:open-in-explorer', { filePath }),
  getLocalSavePath: () => ipcRenderer.invoke('store:get-local-save-path'),
  setLocalSavePath: (path) => ipcRenderer.invoke('store:set-local-save-path', { path }),
  readJsonText: (filePath) => ipcRenderer.invoke('fs:read-json-text', { filePath }),
  writeJsonText: (filePath, content, backupInterval) => ipcRenderer.invoke('fs:write-json-text', { filePath, content, backupInterval }),
  listBackups: (filePath) => ipcRenderer.invoke('fs:list-backups', { filePath }),
  checkBackupHasData: (backupPath) => ipcRenderer.invoke('fs:check-backup-has-data', { backupPath }),
  restoreFromBackup: (backupPath, targetPath) => ipcRenderer.invoke('fs:restore-from-backup', { backupPath, targetPath }),
  deleteBackup: (backupPath) => ipcRenderer.invoke('fs:delete-backup', { backupPath }),
  saveZipBuffer: (filePath, buffer) => ipcRenderer.invoke('fs:save-zip-buffer', { filePath, buffer }),
  getDesktopPath: () => ipcRenderer.invoke('fs:get-desktop-path'),
  isElectron: true,
})