import type { AssistantAction, AssistantActionId, AssistantSkillContract } from './types'

const CONTRACTS: Record<AssistantActionId, AssistantSkillContract> = {
  'image-derive': {
    taskType: 'image-variation',
    objective: '从参考图中提炼简短概念，输出一段只生成单张独立画面、严格沿用参考图视觉参数的图生图提示词。',
    preserve: ['参考图的整体视觉风格与画面参数', '产品或功能语义', '主体尺度与留白'],
    editable: ['核心功能符号或主体隐喻', '必要时一个辅助元素'],
    forbidden: ['要求在同一画面生成组图、套图、多联画或多个方案', '把配色、材质、构图等参考参数改写成无依据的固定描述', '输出思考过程、营销分析、变量词条或多条候选'],
    variationLevel: 'low',
    primaryOutput: 'finalPrompt',
    output: { finalPrompt: true, candidates: false, analysis: false, wordEntries: false },
  },
  'prompt-optimize': {
    taskType: 'prompt-optimize',
    objective: '保持原始意图和事实，将提示词整理为更清晰、可执行的生图指令。',
    preserve: ['产品事实', '品牌', '卖点', '价格和活动机制', '用户已给出的风格、主体和场景'],
    editable: ['描述顺序', '模糊表达', '必要的视觉关系和合规表达'],
    forbidden: ['擅自更换创意方向', '新增卖点', '默认改为信息流广告或竖版', '生成变量词条'],
    variationLevel: 'low',
    primaryOutput: 'finalPrompt',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: false },
  },
  'angle-matrix': {
    taskType: 'creative-expansion',
    objective: '围绕同一产品或素材信息探索不同营销切入角度。',
    preserve: ['产品事实', '品牌', '已确认卖点和合规边界'],
    editable: ['人群切入', '场景', '情绪', '视觉钩子和证明方式'],
    forbidden: ['把推断卖点当作已确认事实'],
    variationLevel: 'high',
    primaryOutput: 'candidate',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: true },
  },
  'batch-variants': {
    taskType: 'creative-expansion',
    objective: '基于一个基准方向创建可归因的 A/B 测试变体。',
    preserve: ['基准方向的产品事实和核心卖点'],
    editable: ['每个测试组中的唯一变量'],
    forbidden: ['在同一候选中同时改变场景、人物、卖点、钩子和版式'],
    variationLevel: 'medium',
    singleVariablePerCandidate: true,
    primaryOutput: 'candidate',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: false },
  },
  'ad-review': {
    taskType: 'review-data',
    objective: '根据用户提供的投放数据分析保留、淘汰和下一轮测试变量。',
    preserve: ['用户提供的数据事实'],
    editable: ['测试建议'],
    forbidden: ['虚构数据结论', '将推断当作事实'],
    variationLevel: 'none',
    primaryOutput: 'analysis',
    output: { finalPrompt: false, candidates: true, analysis: true, wordEntries: false },
  },
  'super-derive': {
    taskType: 'creative-expansion',
    objective: '基于有效素材结构进行较大幅度的创意扩展，产出新的可测试方向。',
    preserve: ['产品事实', '品牌', '已确认卖点和合规边界'],
    editable: ['场景', '人物', '构图', '视觉钩子', '版式和表现手法'],
    forbidden: ['虚构功效、价格、品牌或适用人群'],
    variationLevel: 'high',
    primaryOutput: 'variablePrompt',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: true },
  },
  'market-breakdown': {
    taskType: 'analyze',
    objective: '分析市场或竞品素材的共性结构、差异化机会和风险。',
    preserve: ['输入素材中的可观察事实'],
    editable: ['分析视角和差异化建议'],
    forbidden: ['把单张素材称为市场大盘', '照抄品牌、人物、商标或文案'],
    variationLevel: 'none',
    primaryOutput: 'analysis',
    output: { finalPrompt: false, candidates: false, analysis: true, wordEntries: true },
  },
  'viral-remix': {
    taskType: 'creative-expansion',
    objective: '复刻有效素材的结构逻辑和视觉节奏，不复制其具体内容。',
    preserve: ['信息层级', '视觉节奏', '主体占比关系', '钩子到 CTA 的结构'],
    editable: ['品牌', '产品', '人物', '场景和文案'],
    forbidden: ['照抄品牌、人物、商标、原文案或专有画面'],
    variationLevel: 'high',
    primaryOutput: 'candidate',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: false },
  },
  'image-describe': {
    taskType: 'analyze',
    objective: '忠实拆解参考素材的视觉和广告结构。',
    preserve: ['图片中可观察到的内容'],
    editable: [],
    forbidden: ['擅自生成新素材方向', '把推断内容描述为图片事实'],
    variationLevel: 'none',
    primaryOutput: 'analysis',
    output: { finalPrompt: false, candidates: false, analysis: true, wordEntries: false },
  },
  'style-expand': {
    taskType: 'layout-variation',
    objective: '保持内容和视觉资产不变，探索信息层级和元素位置的不同布局。',
    preserve: ['主体', '人物', '场景', '品牌', '文案内容', '卖点', '色板和视觉风格'],
    editable: ['主体位置', '标题位置', '图文比例', '留白', '信息层级和 CTA 区域位置'],
    forbidden: ['更换视觉风格', '更换场景', '新增人物或卖点'],
    variationLevel: 'medium',
    primaryOutput: 'candidate',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: false },
  },
  'prompt-examples': {
    taskType: 'creative-expansion',
    objective: '提供可供参考的高潜广告素材结构案例。',
    preserve: ['用户提供的产品事实和合规边界'],
    editable: ['案例角度和画面表达'],
    forbidden: ['在无投放数据时声称一定是爆款'],
    variationLevel: 'high',
    primaryOutput: 'candidate',
    output: { finalPrompt: false, candidates: true, analysis: true, wordEntries: false },
  },
  'word-extract': {
    taskType: 'extract-variables',
    objective: '从当前输入中提取已有的、可复用的变量，不凭空扩写。',
    preserve: ['输入中的原始事实和表述'],
    editable: ['变量分类和归纳方式'],
    forbidden: ['凭空生成大量新变量', '输出长句', '生成不在输入中的卖点'],
    variationLevel: 'none',
    primaryOutput: 'analysis',
    output: { finalPrompt: false, candidates: false, analysis: true, wordEntries: true },
  },
  'channel-rewrite': {
    taskType: 'prompt-optimize',
    objective: '保持现有内容和创意方向，仅做目标渠道适配。',
    preserve: ['产品信息', '核心卖点', '价格', '承诺', '适用人群', '活动机制和创意方向'],
    editable: ['画幅', '字幕密度', 'CTA 语气', '平台原生感和审核表达'],
    forbidden: ['重新发散新卖点', '改成无关创意方向'],
    variationLevel: 'low',
    primaryOutput: 'finalPrompt',
    output: { finalPrompt: true, candidates: true, analysis: true, wordEntries: false },
  },
}

export const BUILT_IN_ASSISTANT_ACTIONS: AssistantAction[] = [
  {
    id: 'image-derive',
    name: '概念抽取',
    icon: 'image',
    priority: 120,
    when: { image: 'required', text: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['image-derive'],
  },
  {
    id: 'prompt-optimize',
    name: '提示词优化',
    icon: 'sparkles',
    priority: 115,
    when: { text: 'required', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['prompt-optimize'],
  },
  {
    id: 'angle-matrix',
    name: '角度探索',
    icon: 'wand',
    priority: 100,
    when: { text: 'optional', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['angle-matrix'],
  },
  {
    id: 'batch-variants',
    name: '批量变体',
    icon: 'palette',
    priority: 95,
    when: { text: 'optional', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['batch-variants'],
  },
  {
    id: 'ad-review',
    name: '投放复盘',
    icon: 'tags',
    priority: 90,
    when: { text: 'required', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['ad-review'],
  },
  {
    id: 'super-derive',
    name: '爆款衍生',
    icon: 'wand',
    priority: 70,
    when: { image: 'optional', text: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['super-derive'],
  },
  {
    id: 'market-breakdown',
    name: '大盘拆解',
    icon: 'image',
    priority: 60,
    when: { image: 'optional', text: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['market-breakdown'],
  },
  {
    id: 'viral-remix',
    name: '爆款复刻',
    icon: 'wand',
    priority: 58,
    when: { image: 'optional', text: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['viral-remix'],
  },
  {
    id: 'image-describe',
    name: '素材拆解',
    icon: 'image',
    priority: 55,
    when: { image: 'required', text: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['image-describe'],
  },
  {
    id: 'style-expand',
    name: '版式扩展',
    icon: 'palette',
    priority: 50,
    when: { text: 'optional', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['style-expand'],
  },
  {
    id: 'prompt-examples',
    name: '爆款案例',
    icon: 'thumbs-up',
    priority: 45,
    when: { text: 'optional', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['prompt-examples'],
  },
  {
    id: 'word-extract',
    name: '变量拆解',
    icon: 'tags',
    priority: 40,
    when: { text: 'required', image: 'optional' },
    outputMode: 'create-word-tags',
    contract: CONTRACTS['word-extract'],
  },
  {
    id: 'channel-rewrite',
    name: '渠道改写',
    icon: 'sparkles',
    priority: 10,
    when: { text: 'required', image: 'optional' },
    outputMode: 'show-candidates',
    contract: CONTRACTS['channel-rewrite'],
  },
]

export const BUILT_IN_ASSISTANT_ACTION_IDS = BUILT_IN_ASSISTANT_ACTIONS.map((action) => action.id) as AssistantActionId[]
